from reportlab.lib.units import mm


def add_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        9
    )

    canvas.drawString(
        20,
        20,
        "Generated by StartupForge AI"
    )

    canvas.drawRightString(
        550,
        20,
        f"Page {doc.page}"
    )

    canvas.restoreState()
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib import colors

from datetime import datetime


def create_pdf(
    content,
    filename="startup_blueprint.pdf"
):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]

    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading1"],
        textColor=colors.HexColor("#0f62fe"),
        spaceAfter=12
    )

    body_style = styles["BodyText"]

    story = []

    # -------------------
    # Cover Page
    # -------------------

    story.append(
        Paragraph(
            "🚀 StartupForge AI",
            title_style
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Startup Blueprint Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            body_style
        )
    )

    story.append(Spacer(1, 40))

    story.append(
        Paragraph(
            "Generated by StartupForge AI",
            body_style
        )
    )

    story.append(PageBreak())

    # -------------------
    # Main Content
    # -------------------

    lines = content.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            story.append(Spacer(1, 10))
            continue

        # Detect headings

        if (
            "IDEA ANALYSIS" in line.upper()
            or "MARKET ANALYSIS" in line.upper()
            or "BUSINESS MODEL" in line.upper()
            or "PRODUCT ROADMAP" in line.upper()
            or "STARTUP READINESS SCORE" in line.upper()
        ):

            story.append(
                Spacer(1, 15)
            )

            story.append(
                Paragraph(
                    line,
                    heading_style
                )
            )

            story.append(
                Spacer(1, 10)
            )

        else:

            story.append(
                Paragraph(
                    line,
                    body_style
                )
            )

    pdf.build(
    story,
    onFirstPage=add_footer,
    onLaterPages=add_footer
)

    return filename